CREATE CATALOG IF NOT EXISTS marathos;

USE CATALOG marathos;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS default;
CREATE SCHEMA IF NOT EXISTS information_schema;

CREATE VOLUME IF NOT EXISTS default.raw

